openapi: 3.0.0
info:
  title: PrimeMind AI Internal API
  version: 1.0.0
  description: This is the internal API for handling AI services like the Chatbot.

paths:
  /api/v1/chatbot/prompt:
    post:
      summary: Internal endpoint for initiating a Chatbot interaction
      description: >-
        This endpoint initiates a chat interaction and returns a `promptId` 
        for tracking the conversation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The initial prompt for the Chatbot.
              required:
                - prompt
      responses:
        '200':
          description: Chat initiated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  promptId:
                    type: string
                    description: A unique identifier for the prompt.

  /api/v1/chatbot/prompt/{promptId}:
    get:
      summary: Internal endpoint for retrieving Chatbot Response
      description: >-
        This endpoint retrieves the chatbot response associated with the given `promptId`.
        If the 'completed' field is 'false', another request should be made to get the remaining part 
        of the message. This continues until 'completed' is 'true'.
      parameters:
        - name: promptId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The (potentially partial) message generated by the chatbot.
                  completed:
                    type: boolean
                    description: Indicates if the chatbot has completed generating the full message.
