openapi: 3.0.0
info:
  title: PrimeMind AI Public API
  version: 1.0.0
  description: This API provides access to various AI services including Chatbot, Image Generation, and Image Recognition.

paths:
  /api/v1/chatbot:
    post:
      summary: Interact with Chatbot
      description: >-
        This endpoint validates the provided token for its existence and non-revocation status,
        and checks if the associated workspace has exceeded its usage limit. 
        It then calls the internal /private/api/v1/chatbot API and forwards its response along with 
        the time elapsed in milliseconds (usage) between the request and the response. 
        If the 'completed' field in the response is 'false', the API will automatically 
        send another request after 5 seconds to append the new part of the message to the existing one.
        This behavior continues until 'completed' becomes 'true'.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: The authentication token.
                chatId:
                  type: string
                  description: The optional chat ID to maintain a stateful conversation.
                message:
                  type: string
                  description: The message to send to the chatbot.
                promptId:
                  type: string
                  description: The optional unique identifier for the prompt.
              required:
                - token
                - message
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  chatId:
                    type: string
                    description: The chat ID.
                  message:
                    type: string
                    description: The (potentially partial) response message from the chatbot.
                  completed:
                    type: boolean
                    description: Indicates if the chatbot has completed generating the full response.
                  promptId:
                    type: string
                    description: A unique identifier for the prompt.
                  usage:
                    type: number
                    description: Time elapsed in milliseconds between the request and the response.
        '404':
          description: Invalid token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message. Example: "invalid token"
        '429':
          description: API limit exceeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message. Example: "limit exceeded"
