openapi: 3.0.0
info:
  title: PrimeMind AI Public API
  version: 1.0.0
  description: This API provides access to various AI services including Chatbot, Image Generation, and Image Recognition.

paths:
  /api/v1/chatbot/prompt:
    post:
      summary: Initialize interaction with Chatbot
      description: >-
        This endpoint validates the provided token for its existence and non-revocation status,
        and checks if the associated workspace has exceeded its usage limit. 
        It initiates the chat interaction if it does not exist (there is no chat ID in the request) and provides a prompt ID for tracking the response to the prompt.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: The authentication token.
                chatId:
                  type: string
                  description: The optional chat ID to maintain a stateful conversation.
                prompt:
                  type: string
                  description: The initial prompt to send to the chatbot.
              required:
                - token
                - prompt
      responses:
        '200':
          description: Chat/prompt initialized successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  chatId:
                    type: string
                    description: The chat ID.
                  promptId:
                    type: string
                    description: A unique identifier for the prompt.
        '404':
          description: Invalid token (token does not exist or it was revoked)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message. Example: "invalid token"
        '429':
          description: API limit exceeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message. Example: "limit exceeded"
        '503':
          description: Internal service unavailable.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message. Example: "No response from internal API"
  
  /api/v1/chatbot/{promptId}:
    get:
      summary: Retrieve Chatbot Response
      description: >-
        This endpoint allows for retrieving the chatbot response associated with a specific prompt ID. If the 'completed' field is 'false', another request should be made to get the remaining part of the message. This continues until 'completed' is 'true'.
      parameters:
        - name: promptId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The (potentially partial) response message from the chatbot.
                  completed:
                    type: boolean
                    description: Indicates if the chatbot has completed generating the full response.
                  usage:
                    type: number
                    description: Time elapsed in milliseconds since the initial POST request that generated this prompt.
        '503':
          description: Service unavailable.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message. Example: "No response from chatbot service"
